server:
  port: ${MEDIA_STORAGE_QUERY_SERVICE_PORT:8095}

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${RMTM_MEDIA_STORAGE_QUERY_DB:rmt_mobile_media_storage_query}
    username: ${RMTM_DB_USER:rmt_mobile}
    password: ${RMTM_DB_PASSWORD:rmt_mobile}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:::1}:${KAFKA_PORT:9092}
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${EUREKA_PORT:8761}/eureka/

authentication:
  token:
    key: test

role:
  # Роль Employee нельзя удалить, она базовая
  employee: 579fc993-6123-419a-ae3c-96b0b230f834

department:
  # Отдел, в котором состоит только HRM
  administration: a185b51f-2fd4-4f76-a765-de199d32b000
  # Отдел для тех, кто остался без отдела
  empty: 3a9b4a8a-9e8c-4b72-b3cd-4e72090c259b